### ISSUE TITLE
Git log window doesn't show new commit in submodule

### ISSUE THREAD

**Issue by Ziller90** [mrtrizer/MRUnityGitUI#1]
![image](https://github.com/mrtrizer/MRUnityGitUI/assets/52246558/4a1ead9d-8ca9-44fd-8722-c433dddc01a0)
![image](https://github.com/mrtrizer/MRUnityGitUI/assets/52246558/4b8117a8-858b-4d52-87b1-035adfcf2cf0)

**Comment by Ziller90** [comment]
![image](https://github.com/mrtrizer/MRUnityGitUI/assets/52246558/78146709-34f4-4942-915f-e2ffc38964d3)

**Comment by mrtrizer** [comment]
Should be fixed. Most likely caused by not resetting log cache after fetch.
